### ISSUE TITLE
slow down server response when compare to setInterval

### ISSUE THREAD

**Issue by francisleunggie** [cGuille/async-polling#5]
I have a piece of code that periodically pulls data from a blockchain and pipe the result to a socket.io instance so that it'll emit to its subscribers. If i put that piece in AsyncPolling, the socket.io response time becomes so bad. But it was back to normal when i switch back to setInterval.

**Comment by cGuille** [comment]
Hello !

I have a few questions for you.

1. How long does it take to pull your data from the blockchain **_once_**? Is it something that you would measure in milliseconds? seconds? minutes?
2. How much does the "response time becomes so bad"? Is it a lag that you would measure in milliseconds? seconds? minutes?
3. What delay do you provide to `setInterval()` (second argument)?
4. What delay do you provide to your `AsyncPolling` instance?

**Comment by francisleunggie** [comment]
1. i think about 1/2 to a minute. it's a local geth, reading about 15 blocks only, but it still takes awhile. 
2. when i load the socket io client which is a very small html page, it waited for the server to respond for >1 minute. 
3. i put 3000
4. same, 3000

THanks!

**Comment by cGuille** [comment]
Well, I do not fully understand what your application is doing, but the fact that your `setInterval()` delay (3s)  is shorter than the duration of your scheduled action (≈30s) makes me think that you may have missed something about what `AsyncPolling` does. 

This lib will schedule your action 3000ms after the **_end_** of the previous one, whereas `setInterval()` would blindly call your function every 3000ms regardless of whether the previous action has been done yet or not.
So with `setInterval()`, your function is called every 3s whereas with `AsyncPolling` about every 33s.

That's the whole point of `AsyncPolling`, but that may not be what you need.
I don't know if that's what your problem is about, but it is the only thing I can think of from what you explained.

**Comment by francisleunggie** [comment]
thanks for your explanation on the difference. Though AsyncPolling's behavior is desirable in my case (so that it doesn't overload my server), it somehow blocks socket io from responding to an "on Connection" event to the client. In fact, does it really block at all? from the logs, i saw that socket could only respond when the scheduled task completes. 

the whole point of making it async is to not block... and if it does, i believe that's why socket is not responding as node is single threaded. 

Please let me know thanks!

**Comment by cGuille** [comment]
Sorry I did not respond. I planned to do so and completely forgot. I hope you took another direction in the meantime, but I will answer anyway because I don't like a question without answer.

I think you misunderstood what this library is about. It is merely a wrapper around `setTimeout` to make it more readable to schedule function calls infinitely one after the other.

AsyncPolling is not a parallelism library. It is a library that tries to make it easy to poll a server once in a while dealing with the asynchronous nature of network calls (think XHR) in JS.

So yes, while your task is computing (using the CPU), other part of your application cannot be executed at the same time.
